import os
import json
from urllib.parse import quote

PLAYLIST_DIR = 'playlist'
OUTPUT_FILE = 'js/playlist.js'

# Collect .mp3 files (case-insensitive), keep original casing in names
files = [f for f in os.listdir(PLAYLIST_DIR) if f.lower().endswith('.mp3')]
files.sort(key=lambda s: s.lower())  # stable, case-insensitive sort

# URL-encode each filename as a path segment, then prefix with the folder
# Keep only unreserved URL chars (-._~) and parentheses; encode everything else (spaces -> %20, ' -> %27, Unicode, commas, etc.)
tracks = [f"playlist/{quote(f, safe='-._~()')}" for f in files]

os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by generate_playlist.py — do not edit by hand.\n')
    f.write('const playlistFiles = ')
    json.dump(tracks, f, ensure_ascii=False, indent=2)
    f.write(';\n')
    f.write('window.playlistFiles = playlistFiles;\n')
    f.write('console.log("[diag] playlistFiles defined:", playlistFiles);\n')

print(f"Generated {OUTPUT_FILE} with {len(files)} MP3 files")

